### ISSUE TITLE
How to check phoneme inventories against CLTS

### ISSUE THREAD

**Issue by LinguList** [sigmorphon/2021Task0#12]
Assuming your sigmorphon data in IPA are sound-segmented (space used for segmentation), and your data is a simple table, you can use the following code to check if your data conform to CLTS (https://clts.clld.org).

To get started, download clts and pyclts:

```
$ git clone https://github.com/cldf-clts/clts
$ git clone https://github.com/cldf-clts/pyclts
```

Install pyclts:

```
$ pip install -e pyclts
```

Now, you create the following Python script:

```python
from collections import defaultdict
from pyclts import CLTS
from sys import argv
from tqdm import tqdm as progressbar

bipa = CLTS(argv[1]).bipa

def evaluate(data, indices):
    sounds = defaultdict(list)
    for i, row in progressbar(enumerate(data)):
        for idx in indices:
            for j, t in enumerate(row[idx].split()):
                sounds[t] += [(i, idx, j, row[idx])]
    out = {}
    for t, values in sounds.items():
        sound = bipa[t]
        if sound.type == 'unknownsound':
            out[t, 'unknownsound', '?'] = values
        elif str(sound) != t:
            out[t, sound.name, str(sound)] = values
        else:
            out[t, sound.name, str(sound)] = values
    return out

with open(argv[2]) as f:
    data = [[cell.strip() for cell in row.split('\t')] for row in f]
analysis = evaluate(data, [int(x) for x in argv[3:]])
with open(argv[2]+'-analysis', 'w') as f:
    f.write('SOUND\tCLTS\tALIAS\tFREQUENCY\tNAME\tEXAMPLE\n')
    for (token, name, sound), values in sorted(
            analysis.items(),
            key=lambda x: (len(x[1]), x[0][1], x[0][0]),
            reverse=True):
        f.write('\t'.join([
            token, 
            sound, 
            '*' if token != sound else '',
            str(len(values)),
            name, 
            values[0][3],
            ])+'\n')
```

With this script (save it as `clts.py`, you can now check your file as follows:

```
$ python clts.py PATH/TO/CLTS INPUT/FILE IDXA [IDXB]
```

Here, PATH/TO/CLTS is the path to the folder clts, which you downloaded via git. INPUT/FILE is your file. IDXA is the first index in your file (Python style, count from 0), where segments can be found, you can also check more indices.

**Comment by LinguList** [comment]
Output is a file called INPUT/FILE-analysis. This file shows all sounds and points to potential errors.

**Comment by LinguList** [comment]
If your data is not segmented, you can segment with LingPy (but this does not work always, e.g., it will have problems with affricates like ts, not marked as affricates:

```python
from collections import defaultdict
from pyclts import CLTS
from sys import argv
from tqdm import tqdm as progressbar
from lingpy import ipa2tokens

bipa = CLTS(argv[1]).bipa

def evaluate(data, indices):
    sounds = defaultdict(list)
    for i, row in progressbar(enumerate(data)):
        for idx in indices:
            for j, t in enumerate(ipa2tokens(row[idx])):
                sounds[t] += [(i, idx, j, row[idx])]
    out = {}
    for t, values in sounds.items():
        sound = bipa[t]
        if sound.type == 'unknownsound':
            out[t, 'unknownsound', '?'] = values
        elif str(sound) != t:
            out[t, sound.name, str(sound)] = values
        else:
            out[t, sound.name, str(sound)] = values
    return out

with open(argv[2]) as f:
    data = [[cell.strip() for cell in row.split('\t')] for row in f]
analysis = evaluate(data, [int(x) for x in argv[3:]])
with open(argv[2]+'-analysis', 'w') as f:
    f.write('SOUND\tCLTS\tALIAS\tFREQUENCY\tNAME\tEXAMPLE\n')
    for (token, name, sound), values in sorted(
            analysis.items(),
            key=lambda x: (len(x[1]), x[0][1], x[0][0]),
            reverse=True):
        f.write('\t'.join([
            token, 
            sound, 
            '*' if token != sound else '',
            str(len(values)),
            name, 
            values[0][3],
            ])+'\n')
```

Make sure to install lingpy:

```
$ pip install lingpy
```

and run the code in the same way.

**Comment by ivri** [comment]
Thank you, let me try it now

**Comment by ivri** [comment]
Here is what I got. I can apply the proposed substitutions except "?" cases. For brackets, I would remove them for -ся verbs I mentioned before and manually check others. 

ɫ	lˠ	*	82212	velarized voiced alveolar lateral approximant consonant	ɐ b a ɫ kʲ ɪ n
ɡ	g	*	39099	voiced velar stop consonant	ɐ b a r ɡ ə
t͡ɕ	tɕ	*	35311	voiceless alveolo-palatal sibilant affricate consonant	ɐ a n ɡʲ ɪ t͡ɕ
t͡s	ts	*	29270	voiceless alveolar sibilant affricate consonant	ɐ ɐ r o n ə vʲ ɪ t͡s
⁽ʲ	?	*	10453	unknownsound	ɐ m ⁽ʲ ⁾ pʲ e r
⁾	?	*	10355	unknownsound	ɐ m ⁽ʲ ⁾ pʲ e r
ɡʲ	gʲ	*	7937	palatalized voiced velar stop consonant	ɐ a n ɡʲ ɪ t͡ɕ
t͡sː	tsː	*	3961	long voiceless alveolar sibilant affricate consonant	ɐ b z ɛ t͡sː ɨ r
t͡ɕː	tɕː	*	1205	long voiceless alveolo-palatal sibilant affricate consonant	ɐ f t ɐ m a t͡ɕː ɪ k
d͡ʐ	ɖʐ	*	1019	voiced retroflex sibilant affricate consonant	a b d͡ʐ ʐ ə t
t͡ʂ	ʈʂ	*	835	voiceless retroflex sibilant affricate consonant	a n k ə rʲ ɪ t͡ʂ ʂ
t͡sʲ	tsʲ	*	501	palatalized voiceless alveolar sibilant affricate consonant	b u t͡sʲ sʲ e
d͡z	dz	*	262	voiced alveolar sibilant affricate consonant	ɐ lʲ d͡z ɡʲ e j mʲ ɪ r
⁾ː	?	*	98	unknownsound	bʲ ɪ s ⁽ʲ ⁾ː lʲ e d n ə
d͡zʲ	dzʲ	*	83	palatalized voiced alveolar sibilant affricate consonant	ɐ t ɛ d͡zʲ zʲ ɪ
ɫː	lˠː	*	79	velarized long voiced alveolar lateral approximant consonant	a ɫː ə
ɡː	gː	*	22	long voiced velar stop consonant	b ɛ ɡː r a ʊ n t
‿	?	*	1	unknownsound	d ‿ ə r t ɐ nʲ j a n
ʲ	?	*	1	unknownsound	ʲ

**Comment by LinguList** [comment]
Sounds good, I'd just remove things in little brackets, as they are in brackets anyway, so this is fine. Cases like the bar to join d with ə, I'd remove them, since this is not a valid IPA interpretation in one single case.
