### ISSUE TITLE
English IPA data

### ISSUE THREAD

**Issue by colincwilson** [sigmorphon/2021Task0#13]
The English IPA data released for part 2 of this task contains a lot of errors. There are many instances of spurious vowel changes between the lemma and inflected forms (e.g., [əfɪlieɪt] 'affiliate' has the 3sg present listed as [əfɪliəts], which is a plural not the intended verbal form, [θɹɛt] 'threat' has the present participle listed as [θɹiːtɪŋ]). Affricates are inconsistently transcribed (e.g., [t͡ʃɔk] 'chalk' has the 3sg presented list as [tʃæks], note also the spurious vowel change). There are some past and other forms that I have not encountered before and suspect are not real, such as fret -> frate. (I haven't tried to catalogue the errors comprehensively.)

I have cleaned up the transcriptions by drawing them from an IPA version of the CMU dictionary (available here, https://github.com/menelik3/cmudict-ipa) whenever possible, using the original lemma pronunciations when these weren't available in CMU-IPA, applying the regular rules (with their standard allomorphy) to generate inflected forms that are not in CMU-IPA, and doing some very basic data checking / cleaning. I simplified the transcriptions by removing tie-bars from affricates, syllabic-consonant diacritics, and length marks on vowels; these were inconsistent and aren't needed in a broad transcription. CMU unfortunately has pervasive vacillation between some vowel pairs (e.g., ə ~ ɪ, ɑː ~ ɔ, ɝ ~ ɛr) and I have tried to normalize these within rows (but not across them). There are some remaining entries that I have marked to be checked -- they are relatively few in number and their treatment probably won't matter too much for the task, but it would be nice to eliminate them if they are truly spurious. More generally it would be good for an organizer to look over the revisions that I have made.

Two questions. (1) Who should I send the revised data set to? (2) Many of the errors were located with simple string comparisons (principally, testing whether the lemma is a prefix of an inflected form). Are similar tests going to be applied to ensure a basic level of accuracy for the other languages?

**Comment by ryancotterell** [comment]
Dear Colin,

Please send the errors to me (ryan.cotterell@gmail.com). We are in the process of fixing them. We had
a similar issue with the German data.

I think what we learned is that Wikipron, as a dataset, is not usable its current form for many languages and we are
switching over to CELEX.

Thanks,
--Ryan
