### ISSUE TITLE
Inconsistencies in German IPA?

### ISSUE THREAD

**Issue by LinguList** [sigmorphon/2021Task0#9]
It is not clear to me if this is intended, but I find the German IPA inconsistent in many points. E.g., you use the nasalis sonans in many cases for infinitive endings, like in `abaʁbaɪ̯tn̩`, but then the participle (abarbeitend) is `abaʁbaɪ̯tənt`. Here, the nasalis sonans should also be used in the second form, if one starts using it consequently, as `abaʁbaɪ̯tn̩t` would be the normal pronunciation here (and in both cases, we have variance, between `n̩` and `ən`, but this variance is due to care on speech and education, not due to a following consonant, which the spelling suggests).

Other cases are `olʏmpiastaːdioːn` where the `st` is in fact `ʃt`, following the normal rule by which `st > ʃt` unless in the end of a syllable, and the final o is in fact short (only dialectally, it may be long, but I find this unlikely).

Furthermore `toːdəzɔpfɐ` should be `toːdəsɔpfɐ`, the genitive `s` in `to:dəs` is at a morpheme break, so the rule by which intervocalic `s > z` does not apply. 

`toːləʁants` misses the bar across `ts`, which is then given in the derived forms (`toːləʁant͡sn̩`).		

All in all this looks like it would be very useful to have this double-checked, as these cases may very likely have an impact on machine learning approaches, as these problems invite to regularize what is not a fact of the language.

I haven't checked the other systems, but in general, I recommend to have a look at rather standardized systems of German, like the CELEX data, where they have a large lexicon, to check for these cases.

As to the number of inconsistencies: I am afraid I find them in every fifth item, based on checking the data during the last ten minutes while writing.

**Comment by ivri** [comment]
Thank you for the feedback! We tried various models such as Epitran and SoTA G2P (neural) models (trained on wikipron/wiktionary data).  Would you like to join & help us with German data?

**Comment by LinguList** [comment]
In principle yes, but I may have some time constraints in March - mid 
April. I'd suggest a rather traditional dictionary-based lookup (at 
least for checking) and morphological segmentation of the words you use 
to give algorithms a fairer chance to detect what is going on (since 
morpheme boundaries in compounds are a clear problem).

How long are the lists you use? Are we talking about 1000 words and 
their derivations or rather 100 000?

**Comment by ivri** [comment]
Thank you! I will invite you to our email discussion.
